<div>
    <div class='default'>
	<h2>{tr}How to get started{/tr}</h2>
	<p>
	{tr}This seems to be the first time you run GOsa on this system. To start the GOsa web interface you need a working configuration file, which can be generated by this wizard.{/tr}
	</p>

	<p>
      {tr}What you need to generate a configuration file:{/tr}
	</p>

      <ul>
       <li>{tr}The hostname of your LDAP server{/tr}</li>
       <li>{tr}Installed GOsa and supplementary schema{/tr}</li>
       <li>{tr}The LDAP base of your LDAP directory{/tr}</li>
       <li>{tr}The DN and the password of the LDAP administration user{/tr}</li>
      </ul>
	
	<p>
      {tr}If you've collected the needed information, unlock the setup process like shown in the next paragraph.{/tr}
	</p>

    <hr>
	<h2>{tr}Starting the setup{/tr}</h2>
	<p>
	{tr}For security reasons you need to authenticate the installation by creating the file '/tmp/gosa.auth', containing the current session ID on the servers local filesystem. This can be done by executing the following command:{/tr}
	</p>
	<tt>
	echo -n <b>{$auth_id}</b> &gt; {$path}
	</tt>
	<p>
	{tr}Click the 'Next' button when you've finished.{/tr}
	</p>
     </div>
</div>
